### PR TITLE
[WIP] fix: Match new mappings endpoint response

### PR DESCRIPTION
**Pull request by m-sossich**
[Mappings response change issue](https://github.com/decentraland/content-service/issues/110)

# What? 
Mappings endpoint format change fix

# Why? 
It is explained in the linked issue

### CODE REVIEW

**Comment by menduz** [comment]
Changes in `Preview.ts` are required to merge this PR

**Comment by fmiras** [comment]
Waiting for the release and deployment of the new content server.

**Comment by eordano** [comment]
Can we merge this now? 

cc: @fmiras @m-sossich

**Comment by menduz** [comment]
https://github.com/decentraland/cli/pull/420 fixes this

**Pull request closed without merging**
