### PR TITLE
Upgrade preview.js to latest CLI

### LINKED ISSUE #59: TypeError: Cannot convert undefined or null to object
cli doesn't seem to support a-entity objects, although it is listed as supported here:
https://wiki.decentraland.org/index.php?title=A-Minus#Supported_entities

sample scene:
```
<a-scene>
      <a-entity position='5 0 0' rotation='0 90 0'>
        <a-box color='#ff00aa' position='-2 0 0' />
        <a-box color='#00aaff' position='2 0 0' />
      </a-entity>
    </a-scene>
```

### PR DESCRIPTION
**Pull request by bnolan**
Fixes #59

Uses the latest version of preview.js from the client. Features:

* new sky model
* no physics
* no shadows
* more a-frame primitives supported

screen shot 2018-02-28 at 10 36 19 am

### CODE REVIEW

**Comment by michaltakac** [comment]
`dcl init` copies the `preview.js` from where `cli` is installed globally, to local dcl project:
https://github.com/decentraland/cli/blob/master/src/utils/generate-html.ts#L17

Can you update the `dcl upgrade` command to also remove+copy `preview.js` to `.decentraland` folder?
https://github.com/decentraland/cli/blob/master/src/commands/upgrade.ts#L30-L31

**Comment by bnolan** [comment]
Ok yup, was wondering how `upgrade` would work, I'll fix that.

**Comment by rushughes** [comment]
ive got this branch deployed locally and it mostly works, however with consistency .obj/.mtl pairs exported from 3d studio max that work fine in a-frame, do not work in the dcl client scene generator when the .mtl file is specified.

for now my  models are private but i will see if i can get my artist to create a quick test model i can share with you to demonstrate the problem

**Comment by rushughes** [comment]
[Test.zip](https://github.com/decentraland/cli/files/1770577/Test.zip)

Nothing shows with 
`      <a-obj-model
      obj-model="obj: models/HelloTestPink.obj; mtl: models/HelloTestPink.mtl;"
      position="0 0 0"
      rotation="0 0 0"
      scale="0.5 0.5 0.5"
      ></a-obj-model>
`

if i remove the mtl it works fine tho

`      <a-obj-model
      obj-model="obj: models/HelloTestPink.obj;"
      position="0 0 0"
      rotation="0 0 0"
      scale="0.5 0.5 0.5"
      ></a-obj-model>
`

this happens with everything we are exporting from 3dsmax

**Comment by bnolan** [comment]
@michaltakac I've created an issue (https://github.com/decentraland/cli/issues/80) to upgrade the preview.js with `dcl upgrade`.

**Pull request merged**
